evernote_blog/evernote_blog/Models/ClassifyInfo.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace evernote_blog.Models
{
    [Table("classify_info")]
    public class ClassifyInfo
    {
        /// <summary>
        /// 编号
        /// </summary>
        [Column("id")]
        public int Id { get; set; }

        /// <summary>
        /// 标题
        /// </summary>
        [Column("classify_name")]
        public string ClassifyName { get; set; }

        /// <summary>
        /// 分类编号
        /// </summary>
        [Column("parent_id")]
        public int ParentId { get; set; }

        /// <summary>
        /// 分类Evernote编号
        /// </summary>
        [Column("guid")]
        public string Guid { get; set; }

    }
}

evernote_blog/evernote_blog/Models/DataContext.cs
using Microsoft.EntityFrameworkCore;

namespace evernote_blog.Models
{
    public class DataContext : DbContext
    {
        public DataContext(DbContextOptions<DataContext> options)
            : base(options)
        {
        }

        public DbSet<NoteInfo> NoteData { get; set; }

        public DbSet<ClassifyInfo> ClassifyData { get; set; }
    }
}

evernote_blog/evernote_blog/Models/ErrorViewModel.cs
using System;

namespace evernote_blog.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

evernote_blog/evernote_blog/Models/NoteInfo.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace evernote_blog.Models
{
    [Table("note_info")]
    public class NoteInfo
    {
        /// <summary>
        /// 编号
        /// </summary>
        [Column("id")]
        public int Id { get; set; }

        /// <summary>
        /// 标题
        /// </summary>
        [Column("title")]
        public string Title { get; set; }

        /// <summary>
        /// 分类编号
        /// </summary>
        [Column("classify_id")]
        public int ClassifyId { get; set; }

        /// <summary>
        /// 是否是博客文章
        /// </summary>
        [Column("is_blog")]
        public int IsBlog { get; set; }

        /// <summary>
        /// 标签
        /// </summary>
        [Column("tags")]
        public string Tags { get; set; }

        /// <summary>
        /// 文章内容文件名称
        /// </summary>
        [Column("content")]
        public string Content { get; set; }

        /// <summary>
        /// 文章内容摘要
        /// </summary>
        [Column("content_snippet")]
        public string ContentSnippet { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Column("create_time")]
        public long CreateTime { get; set; }

        /// <summary>
        /// 修改时间
        /// </summary>
        [Column("update_time")]
        public long UpdateTime { get; set; }

        /// <summary>
        /// 笔记Evernote编号
        /// </summary>
        [Column("note_guid")]
        public string NoteGuid { get; set; }

        ///// <summary>
        ///// 分类
        ///// </summary>
        //public ClassifyInfo ClassifyInfo { get; set; }

    }

    public class ShowNoteClassifyInfo
    {
        /// <summary>
        /// 分类编号
        /// </summary>
        public int ClassifyId { get; set; }


        /// <summary>
        /// 分类名称
        /// </summary>
        public string ClassifyName { get; set; }

        /// <summary>
        /// 笔记本数
        /// </summary>
        public int NoteCount { get; set; }
    }
}

evernote_blog/evernote_blog/Controllers/ErrorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace evernote_blog.Controllers
{
    public class ErrorController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

evernote_blog/evernote_blog/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using evernote_blog.Models;

namespace evernote_blog.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

evernote_blog/evernote_blog/Controllers/NoteDetailController.cs
using evernote_blog.Common;
using evernote_blog.DataAccess.Implement;
using evernote_blog.Models;
using Microsoft.AspNetCore.Mvc;

namespace evernote_blog.Controllers
{
    public class NoteDetailController : Controller
    {
        private readonly NoteInfoDb _noteInfoDb;

        public NoteDetailController(DataContext context)
        {
            CommonUnit.Context = context;
            _noteInfoDb = new NoteInfoDb(context);
        }

        public IActionResult Index(string guid)
        {
            if (string.IsNullOrWhiteSpace(guid))
            {
                return RedirectToAction("Index", "Error");
            }
            ViewBag.NoteInfo = _noteInfoDb.GetNoteInfoByGuid(guid);
            ViewBag.ShowNoteClassifyInfo = _noteInfoDb.GetClassifyIdList();
            return View();
        }
    }
}

evernote_blog/evernote_blog/Controllers/NoteInfoesController.cs
using evernote_blog.Common;
using evernote_blog.DataAccess.Implement;
using evernote_blog.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace evernote_blog.Controllers
{
    public class NoteInfoesController : Controller
    {
        private readonly NoteInfoDb _noteInfoDb;

        private static int _classifyId = 0;
        private static int _pageIndex = 1;
        private static string _searchText = string.Empty;
        private static long _createTime = 1;
        private int _pageSum = 0;
        private int _pageSize = 10;

        public NoteInfoesController(DataContext context)
        {
            CommonUnit.Context = context;
            _noteInfoDb = new NoteInfoDb(context);
            var count = _noteInfoDb.GetNoteInfoCount();
            _pageSum = (int)Math.Ceiling(count / (double)_pageSize);

        }

        // GET: NoteInfoes
        //[ResponseCache(Duration = 600)]
        public IActionResult Index(string type = "", int pageIndex = 0, int classifyId = 0, string searchText = "", long createTime = 0)
        {

            switch (type)
            {
                case "first":
                case "end":
                case "last":
                case "next":
                case "skip":
                    _classifyId = classifyId > 0 ? classifyId : _classifyId;
                    _pageIndex = pageIndex > 0 ? pageIndex : _pageIndex;
                    _searchText = !string.IsNullOrWhiteSpace(searchText) ? searchText : _searchText;
                    _createTime = createTime > 0 ? createTime : _createTime;
                    break;

                case "search":
                case "className":
                case "createTime":
                    _classifyId = 0;
                    _pageIndex = 1;
                    _createTime = 0;

                    switch (type)
                    {
                        case "search":
                            _searchText = !string.IsNullOrWhiteSpace(searchText) ? searchText : _searchText;
                            break;
                        case "className":
                            _classifyId = classifyId > 0 ? classifyId : _classifyId;
                            break;
                        case "createTime":
                            _createTime = createTime > 0 ? createTime : _createTime;
                            break;
                    }
                    break;
                default:
                    _classifyId = 0;
                    _pageIndex = 1;
                    _searchText = string.Empty;
                    _createTime = 0;
                    break;
            }

            var n = 5;
            var data = _noteInfoDb.GetNoteInfoByPage(out var pageSum, out _pageIndex, type, _pageIndex, _pageSize, _classifyId, _searchText, _createTime);

            //banner博客数据
            ViewBag.BannerNoteInfo = _noteInfoDb.GetNewestNOteInfos();

            ViewBag.NoteInfo = data;
            ViewBag.PageIndex = _pageIndex;
            ViewBag.PageStrList = CommonUnit.GetPageStrList(pageSum, _pageIndex);
            ViewBag.ShowNoteClassifyInfo = _noteInfoDb.GetClassifyIdList();
            return View();
        }
    }
}

evernote_blog/evernote_blog/Views/NoteDetail/Index.cshtml
@using evernote_blog.Common
@{
}
<!--================Home Banner Area =================-->
<section class="banner_area">
    <div class="container">
        <div class="row banner_inner">
            <div class="col-lg-5"></div>
            <div class="col-lg-7">
                <div class="banner_content text-center">
                    <h2>BLOG CONTENT</h2>
                    <div class="page_link">
                        <a asp-controller="NoteInfoes" asp-action="Index">Blog</a>
                        <a>Blog Content</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!--================End Home Banner Area =================-->
<!--================Blog Area =================-->
<section class="blog_area p_120 single-post-area">
    <div class="container">
        <div class="row">

            <div class="col-lg-8">
                <div class="main_blog_details">
                    <img class="img-fluid" src="img/blog/news-blog.jpg" alt="">
                    <a href="#"><h4>@ViewBag.NoteInfo.Title</h4></a>
                    <div class="user_details">
                        <div class="float-left">
                            <a class="cat_btn" onclick="SearchNoteByClassifyId(@ViewBag.NoteInfo.ClassifyId)">@CommonUnit.GetClassifyName(ViewBag.NoteInfo.ClassifyId)</a>
                        </div>
                        @*<div class="float-right">
                                <div class="media">
                                    <div class="media-body">
                                        <h5>Mark wiens</h5>
                                        <p>12 Dec, 2017 11:21 am</p>
                                    </div>
                                    <div class="d-flex">
                                        <img src="img/blog/user-img.jpg" alt="">
                                    </div>
                                </div>
                            </div>*@
                    </div>
                    @Html.Raw(System.Net.WebUtility.UrlDecode(@CommonUnit.GetNoteContent(ViewBag.NoteInfo.Content)))

                    @*<div class="news_d_footer">
                            <a href="#"><i class="lnr lnr lnr-heart"></i>Lily and 4 people like this</a>
                            <a class="justify-content-center ml-auto" href="#"><i class="lnr lnr lnr-bubble"></i>06 Comments</a>
                            <div class="news_socail ml-auto">
                                <a href="#"><i class="fa fa-facebook"></i></a>
                                <a href="#"><i class="fa fa-twitter"></i></a>
                                <a href="#"><i class="fa fa-youtube-play"></i></a>
                                <a href="#"><i class="fa fa-pinterest"></i></a>
                                <a href="#"><i class="fa fa-rss"></i></a>
                            </div>
                        </div>*@
                </div>
            </div>

            @await Html.PartialAsync("_BlogUserSection", (List<ShowNoteClassifyInfo>)ViewBag.ShowNoteClassifyInfo)
        </div>
    </div>
</section>
<!--================Blog Area =================-->

<div id="outerdiv" style="position:fixed;top:0;left:0;background:rgba(0,0,0,0.7);z-index:2;width:100%;height:100%;display:none;">
    <div id="innerdiv" style="display: flex;justify-content: center;align-items: center; height: 100%;">
        <img id="bigimg" style="border:5px solid #fff; max-width: 100%;" src="" />
    </div>
</div>

<script type="text/javascript">

    $(function () {
        $(".main_blog_details img").click(function () {
            var _this = $(this);//将当前的pimg元素作为_this传入函数
            imgShow("#outerdiv", "#innerdiv", "#bigimg", _this);
        });
    });

    function imgShow(outerdiv, innerdiv, bigimg, _this) {
        var src = _this.attr("src");//获取当前点击的pimg元素中的src属性
        $(bigimg).attr("src", src);//设置#bigimg元素的src属性
        $(outerdiv).css("display", "block");
        $(innerdiv).click(function () {
            $(outerdiv).css("display", "none");
        });
    }

</script>

evernote_blog/evernote_blog/Views/NoteInfoes/Index.cshtml
@using evernote_blog.Common
@{
    //Layout = null;

}


@if (ViewBag.BannerNoteInfo != null && ViewBag.BannerNoteInfo.Count > 0)
{
    <!--================Home Banner Area =================-->
    <section class="home_banner_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-5"></div>
                <div class="col-lg-7">
                    <div class="blog_text_slider owl-carousel">
                        @foreach (var noteInfoItem in ViewBag.BannerNoteInfo)
                        {
                            <div class="item">
                                <div class="blog_text">
                                    <div class="cat">
                                        <a class="cat_btn" onclick="SearchNoteByClassifyId(@noteInfoItem.ClassifyId)">@CommonUnit.GetClassifyName(noteInfoItem.ClassifyId)</a>
                                        <a onclick="SearchNoteByCreateTime(@noteInfoItem.CreateTime)"><i class="fa fa-calendar" aria-hidden="true"></i> @CommonUnit.FormatTime(noteInfoItem.CreateTime)</a>
                                    </div>
                                    <a asp-controller="NoteDetail" asp-action="Index" asp-route-guid="@noteInfoItem.NoteGuid"><h4>@noteInfoItem.Title</h4></a>
                                    <p style="overflow-x: hidden;">@noteInfoItem.ContentSnippet</p>
                                    <a class="blog_btn" asp-controller="NoteDetail" asp-action="Index" asp-route-guid="@noteInfoItem.NoteGuid">Read More</a>
                                </div>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================End Home Banner Area =================-->
}

<!--================Blog Area =================-->
<section class="blog_area p_120">
    <div class="container">
        <div class="row">
            <div class="col-lg-8">
                <div class="blog_left_sidebar">
                    @foreach (var noteInfoItem in ViewBag.NoteInfo)
                    {
                        <article class="blog_style1">
                            <div class="blog_img">
                                <img class="img-fluid" src="@CommonUnit.GetBlogImageStr()" alt="">
                            </div>
                            <div class="blog_text">
                                <div class="blog_text_inner">
                                    <div class="cat">
                                        <a class="cat_btn" onclick="SearchNoteByClassifyId(@noteInfoItem.ClassifyId)">@CommonUnit.GetClassifyName(noteInfoItem.ClassifyId)</a>
                                        <a onclick="SearchNoteByCreateTime(@noteInfoItem.CreateTime)"><i class="fa fa-calendar" aria-hidden="true"></i> @CommonUnit.FormatTime(noteInfoItem.CreateTime)</a>
                                        @*<a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 05</a>*@
                                    </div>
                                    <a asp-controller="NoteDetail" asp-action="Index" asp-route-guid="@noteInfoItem.NoteGuid"><h4>@noteInfoItem.Title</h4></a>
                                    <p style="overflow-x: hidden;">@noteInfoItem.ContentSnippet</p>
                                    <a class="blog_btn" asp-controller="NoteDetail" asp-action="Index" asp-route-guid="@noteInfoItem.NoteGuid">Read More</a>
                                </div>
                            </div>
                        </article>
                    }

                    @*分页*@
                    <nav class="blog-pagination justify-content-center d-flex page">
                        <ul class="pagination">
                            <li class="page-item">
                                <a asp-action="Index" asp-route-type="first" class="page-link" aria-label="Previous">
                                    <span aria-hidden="true" style="position: relative;">
                                        <span class="lnr lnr-chevron-left" style="position: absolute; left: -5px; top: -1px;"></span>  &nbsp;&nbsp;
                                        <span class="lnr lnr-chevron-left" style="position: absolute; left: 5px; top: -1px;"></span>
                                    </span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a asp-action="Index" asp-route-type="last" class="page-link" aria-label="Previous">
                                    <span aria-hidden="true">
                                        <span class="lnr lnr-chevron-left"></span>
                                    </span>
                                </a>
                            </li>

                            @foreach (var pageStr in ViewBag.PageStrList)
                            {
                                if (pageStr.ToString() == ViewBag.PageIndex.ToString())
                                {
                                    <li class="page-item active">
                                        <a asp-action="Index" asp-route-type="skip" asp-route-pageIndex="@pageStr" class="page-link">@pageStr</a>
                                    </li>
                                }
                                else
                                {
                                    <li class="page-item">
                                        <a asp-action="Index" asp-route-type="skip" asp-route-pageIndex="@pageStr" class="page-link">@pageStr</a>
                                    </li>
                                }
                            }


                            <li class="page-item">
                                <a asp-action="Index" asp-route-type="next" class="page-link" aria-label="Next">
                                    <span aria-hidden="true">
                                        <span class="lnr lnr-chevron-right"></span>
                                    </span>
                                </a>
                            </li>
                            <li class="page-item">
                                <a asp-action="Index" asp-route-type="end" class="page-link" aria-label="Next">
                                    <span aria-hidden="true" style="position: relative;">
                                        <span class="lnr lnr-chevron-right" style="position: absolute; left: -5px; top: -1px;"></span>  &nbsp;&nbsp;
                                        <span class="lnr lnr-chevron-right" style="position: absolute; left: 5px; top: -1px;"></span>
                                    </span>
                                </a>
                            </li>
                        </ul>
                        <div class="input-group" style="width: 80px; position: relative; display: none;">
                            <input type="text" id="inputGoToPage" class="form-control" placeholder="" oninput="value=value.replace(/[^\d]/g,'')" style="padding-right: 33px; border-top-right-radius: .25rem; border-bottom-right-radius: .25rem;">
                            <span class="input-group-btn" style="line-height: 42px; text-align: center; position: absolute; right: 5px; z-index: 20;">
                                <a id="inputGoToPageAction" href="" onclick="goToPage()"><i class="lnr lnr-arrow-right"></i></a>
                            </span>
                        </div>
                    </nav>
                </div>
            </div>

            @await Html.PartialAsync("_BlogUserSection", (List<ShowNoteClassifyInfo>)ViewBag.ShowNoteClassifyInfo)

        </div>
    </div>
</section>
<!--================Blog Area =================-->
<script>

    //跳转回车事件
    $('#inputGoToPage').bind('keyup', function (event) {
        if (event.keyCode == "13") {
            $('#inputGoToPageAction').click();
        }

    });
</script>

evernote_blog/evernote_blog/Views/NoteInfos.cshtml
@model evernote_blog.Models.NoteInfo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>NoteInfos</title>
</head>
<body>

<div>
    <h4>NoteInfo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Title)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Title)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ClassifyId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ClassifyId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.IsBlog)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.IsBlog)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tags)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Content)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Content)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CreateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CreateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.UpdateTime)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.UpdateTime)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NoteGuid)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NoteGuid)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>
</body>
</html>

evernote_blog/evernote_blog/Views/Shared/_BlogUserSection.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="col-lg-4">
    <div class="blog_right_sidebar">
        <aside class="single_sidebar_widget search_widget">
            <div class="input-group">
                <input type="text" class="form-control" placeholder="Search Posts" id="searchText">
                <span class="input-group-btn">
                    <button id="searchTextButton" class="btn btn-default" type="button" onclick="SearchNoteBySearchText();"><i class="lnr lnr-magnifier"></i></button>
                </span>
            </div><!-- /input-group -->
            <div class="br"></div>
        </aside>
        <aside class="single_sidebar_widget author_widget">
            <img class="author_img img-fluid" src="~/img/blog/author.jpg" alt="" style="border-radius: 5px;">
            <h4>Tinhead</h4>
            @*<p>Senior blog writer</p>*@
            <p>这个人很懒，什么介绍也不写</p>
            @*<div class="social_icon">
                <a href="#"><i class="fa fa-facebook"></i></a>
                <a href="#"><i class="fa fa-twitter"></i></a>
                <a href="#"><i class="fa fa-github"></i></a>
                <a href="#"><i class="fa fa-behance"></i></a>
            </div>*@
            <div class="br"></div>
        </aside>
        
        <aside class="single_sidebar_widget post_category_widget">
            <h4 class="widget_title">Post Catgories</h4>
            <ul class="list cat-list">
                @foreach (var showNoteClassifyInfo in ViewBag.ShowNoteClassifyInfo)
                {
                    <li>
                        <a class="d-flex justify-content-between" onclick="SearchNoteByClassifyId(@showNoteClassifyInfo.ClassifyId);">
                            <p>@showNoteClassifyInfo.ClassifyName</p>
                            <p>@showNoteClassifyInfo.NoteCount</p>
                        </a>
                    </li>
                }
            </ul>
        </aside>
    </div>
</div>
<script>

    //查询回车事件
    $('#searchText').bind('keyup', function (event) {
        if (event.keyCode == "13") {
            $('#searchTextButton').click();
        }

    });
</script>